<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Chronoscope.Agent.Collectors.Windows\Chronoscope.Agent.Collectors.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="2.10.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
