<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Chronoscope.Agent\Chronoscope.Agent.csproj" />
    <ProjectReference Include="..\Chronoscope.Agent.Collectors.Windows\Chronoscope.Agent.Collectors.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
